### ISSUE TITLE
Broadcast Feature is messed up!

### ISSUE THREAD

**Issue by AnonyGitty** [Itz-fork/Callsmusic-Plus#13]
Ikr this is weird but I found /broadcast command is some kind of broken up. but /chatcast is working fine and It'll do the job huh? So what if you remove /broadcast command and replace it with /chatcast command feature?

**Comment by Itz-fork** [comment]
> Ikr this is weird but I found /broadcast command is some kind of broken up.
Yeah it's broken up due to error in user id collect! For now it's a unnecessary command!

> but /chatcast is working fine and It'll do the job huh?
Yes `/chatcast` command is woring fine! and yes it will do the job but the job! (Not sure as it's giving some errors while broadcasting

> So what if you remove /broadcast command and replace it with /chatcast command feature?
Yeah Me Also thinking about this! This is the best way to solve it :laughing: lol!

**Comment by Itz-fork** [comment]
@AnonyGitty Check Now! Did a small change in code. Added `chat` instead of `from_user` to avoid saving unwanted user id's in db! but yeah still don't think the problem was solved! :D

**Comment by AnonyGitty** [comment]
> @AnonyGitty Check Now! Did a small change in code. Added `chat` instead of `from_user` to avoid saving unwanted user id's in db! but yeah still don't think the problem was solved! :D

Seems like it's fixed now. Thanks for the time!
